// lib/products.js  ← taruh di folder lib/ atau data/

export const products = [
    {
        id: 1,
        slug: "vivo-y21",
        image: "/test1.png",
        images: ["/test1.png", "/test1.png", "/test1.png"],
        brand: "Vivo",
        title: "Vivo Y21",
        subtitle: "Harga Jual",
        badge: "Terlaris",
        price: 2299000,
        originalPrice: 2599000,
        rating: 4.5,
        reviews: 128,
        stock: 15,
        colors: ["Metallic Blue", "Diamond Glow"],
        storage: ["64GB", "128GB"],
        description:
            "Vivo Y21 hadir dengan desain elegan dan performa handal untuk kebutuhan sehari-hari. Dilengkapi baterai besar 5000mAh yang tahan lama sehingga aktivitasmu tidak pernah terhenti.",
        highlights: [
            "Layar 6.51 inci HD+ IPS LCD",
            "Baterai 5000mAh dengan pengisian 18W",
            "Kamera utama 13MP + 2MP",
            "RAM 4GB + ROM 64GB (dapat diperluas)",
        ],
        specs: {
            Jaringan: "4G LTE / 3G / 2G",
            Layar: "6.51 inci, HD+ (1600×720), IPS LCD",
            Prosesor: "MediaTek Helio P35 (12nm)",
            RAM: "4 GB",
            Penyimpanan: "64 GB (microSD hingga 1TB)",
            "Kamera Belakang": "13MP (f/2.2) + 2MP (f/2.4)",
            "Kamera Depan": "8MP (f/1.8)",
            Baterai: "5000mAh, pengisian 18W",
            OS: "Android 11 + Funtouch OS 11.1",
            Dimensi: "164.26 × 76.08 × 8.0mm, 183g",
            SIM: "Dual SIM (Nano)",
            Warna: "Metallic Blue, Diamond Glow",
        },
    },
    {
        id: 2,
        slug: "vivo-y21d",
        image: "/test1.png",
        images: ["/test1.png", "/test1.png", "/test1.png"],
        brand: "Vivo",
        title: "Vivo Y21d",
        subtitle: "Harga Jual",
        badge: "Baru",
        price: 1999000,
        originalPrice: 2199000,
        rating: 4.2,
        reviews: 56,
        stock: 8,
        colors: ["Diamond Glow", "Midnight Blue"],
        storage: ["64GB"],
        description:
            "Vivo Y21d adalah pilihan cerdas dengan layar luas dan baterai berkapasitas besar, cocok untuk hiburan dan produktivitas sehari-hari.",
        highlights: [
            "Layar 6.51 inci HD+ IPS",
            "Baterai 6000mAh",
            "Kamera 13MP AI Triple Camera",
            "Fast Charging 18W",
        ],
        specs: {
            Jaringan: "4G LTE / 3G / 2G",
            Layar: "6.51 inci, HD+ (1600×720), IPS LCD",
            Prosesor: "MediaTek Helio P35",
            RAM: "3 GB",
            Penyimpanan: "64 GB",
            "Kamera Belakang": "13MP + 2MP + 2MP",
            "Kamera Depan": "8MP",
            Baterai: "6000mAh, pengisian 18W",
            OS: "Android 11 + Funtouch OS 11.1",
            Dimensi: "164.5 × 76.0 × 8.3mm, 190g",
            SIM: "Dual SIM (Nano)",
            Warna: "Diamond Glow, Midnight Blue",
        },
    },
    {
        id: 3,
        slug: "vivo-x300",
        image: "/test1.png",
        images: ["/test1.png", "/test1.png", "/test1.png"],
        brand: "Vivo",
        title: "Vivo X300",
        subtitle: "Harga Jual",
        badge: "Flagship",
        price: 8999000,
        originalPrice: 9499000,
        rating: 4.8,
        reviews: 312,
        stock: 5,
        colors: ["Titanium Black", "Pearl White"],
        storage: ["256GB", "512GB"],
        description:
            "Vivo X300 adalah smartphone flagship dengan kamera periskop 200MP dan chipset generasi terbaru. Performa tak tertandingi dengan desain premium yang memukau.",
        highlights: [
            "Kamera Periskop 200MP Zeiss",
            "Dimensity 9300+, 12GB RAM",
            "Layar AMOLED 6.78 inci 144Hz",
            "Pengisian 120W + 50W Wireless",
        ],
        specs: {
            Jaringan: "5G / 4G LTE / 3G / 2G",
            Layar: "6.78 inci, 2K AMOLED, 144Hz",
            Prosesor: "MediaTek Dimensity 9300+",
            RAM: "12 GB LPDDR5X",
            Penyimpanan: "256 GB UFS 4.0",
            "Kamera Belakang": "200MP Periskop + 50MP Ultra Wide + 12MP",
            "Kamera Depan": "32MP",
            Baterai: "5500mAh, 120W FlashCharge",
            OS: "Android 14 + Funtouch OS 14",
            Dimensi: "163.0 × 75.5 × 8.4mm, 215g",
            SIM: "Dual SIM (Nano)",
            Warna: "Titanium Black, Pearl White",
        },
    },
    {
        id: 4,
        slug: "vivo-v30-pro",
        image: "/test1.png",
        images: ["/test1.png", "/test1.png", "/test1.png"],
        brand: "Vivo",
        title: "Vivo V30 Pro",
        subtitle: "Harga Jual",
        badge: null,
        price: 6499000,
        originalPrice: 6999000,
        rating: 4.6,
        reviews: 204,
        stock: 12,
        colors: ["Peacock Green", "Silk Red"],
        storage: ["256GB"],
        description:
            "Vivo V30 Pro menghadirkan kamera Aura Light Portrait terbaik di kelasnya dengan desain ramping yang elegan. Cocok untuk para content creator dan pecinta fotografi.",
        highlights: [
            "Kamera Portrait 50MP ZEISS",
            "Aura Light 3.0 LED",
            "Snapdragon 8s Gen 2",
            "Layar AMOLED 120Hz Curved",
        ],
        specs: {
            Jaringan: "5G / 4G LTE",
            Layar: "6.78 inci, 1.5K AMOLED, 120Hz, Curved",
            Prosesor: "Snapdragon 8s Gen 2",
            RAM: "12 GB",
            Penyimpanan: "256 GB",
            "Kamera Belakang": "50MP ZEISS + 50MP Ultra Wide + 12MP Tele",
            "Kamera Depan": "50MP",
            Baterai: "5000mAh, 80W FlashCharge",
            OS: "Android 14 + Funtouch OS 14",
            Dimensi: "164.4 × 74.9 × 7.46mm, 186g",
            SIM: "Dual SIM (Nano)",
            Warna: "Peacock Green, Silk Red",
        },
    },
];

export function getProductBySlug(slug) {
    return products.find((p) => p.slug === slug) || null;
}

export function formatPrice(price) {
    return new Intl.NumberFormat("id-ID", {
        style: "currency",
        currency: "IDR",
        minimumFractionDigits: 0,
    }).format(price);
}